# Generated by Django 5.0.6 on 2024-06-09 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='created_at',
        ),
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.CharField(default='No description', max_length=500),
        ),
        migrations.AddField(
            model_name='history',
            name='keyword',
            field=models.CharField(default='No keyword', max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
