# Generated by Django 5.0.6 on 2024-06-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_history_created_at_history_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='keyword',
        ),
        migrations.AddField(
            model_name='history',
            name='country',
            field=models.CharField(choices=[('MY', 'Malaysia'), ('IN', 'India'), ('CN', 'China'), ('KR', 'South Korea'), ('QA', 'Qatar')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='offensive',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
