# Generated by Django 5.0.6 on 2024-07-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_history_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Prefer not to say')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
