# Generated by Django 5.0.6 on 2024-08-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
